### ISSUE TITLE
为什么打开dist文件夹里的index.html会报错

### ISSUE THREAD

**Issue by avocadowang** [Sioxas/vue-music#12]
Uncaught TypeError: t.util.isObject is not a function
<img width="662" alt="console" src="https://cloud.githubusercontent.com/assets/18697326/23337985/9a2d3af8-fc39-11e6-88f4-94e39b7dcc97.png">

**Comment by ZJN-banana** [comment]
#13 fixed

**Comment by avocadowang** [comment]
@ZJN-banana 没看懂啊 -_-||,能详细说一下么

**Comment by Sioxas** [comment]
重新运行一下npm install

**Comment by avocadowang** [comment]
@Sioxas 👌
