### ISSUE TITLE
请问这个项目怎么学习呢？

### ISSUE THREAD

**Issue by BlythDD** [Sioxas/vue-music#21]
表示初学者；不太明白script和link各是怎么引用的；
main.js都有什么内容；
app.vue；也没有找到浏览器中的相关app.js； import Search from './components/Search'是什么意思？
是否有一个合适的东西(注释类似)的东西适合学习的？

**Comment by yyuxiang** [comment]
建议先把vue官方文档多看两遍，里面有很多小demo可以比着敲几遍
