### ISSUE TITLE
轮播图空白问题  , 处理

### ISSUE THREAD

**Issue by hugeIcofont** [Sioxas/vue-music#30]
轮播的空白问题,是因为没有引入vue-awesome-swiper组件引起的, 加上代码就好了;
在 main.js 中 加入以下代码即可: 
import VueAwesomeSwiper from 'vue-awesome-swiper'
import 'swiper/dist/css/swiper.css'
Vue.use(VueAwesomeSwiper)

**Comment by Sioxas** [comment]
Thanks
