### ISSUE TITLE
可恶啊，qq的歌词做了referer防盗链

### ISSUE THREAD

**Issue by doxiaodong** [Sioxas/vue-music#4]
不想在后端做接口啊

**Comment by doxiaodong** [comment]
后端还是厉害啊，强行改了 `referer`
https://api.darlin.me/music/lyric/97773/?callback=jsonp_1481270574993_60382

**Comment by FlyerJay** [comment]
防盗链只能改后端referer吗

**Comment by Sioxas** [comment]
我也想加歌词，可以用你的api么？

**Comment by doxiaodong** [comment]
@Sioxas 当然可以～

**Comment by doxiaodong** [comment]
https://github.com/doxiaodong/letsencrypt-nginx-proxy/commit/cd864bf7ebc52520c53bb2c2cc677dad37a4b67a

刚刚更新 nginx 配置的时候搞错了，导致 api.darlin.me/music 挂了两小时
